fix(clippy): use `or_else` for get_var("HOME") call
instead of `or`
error: function call inside of `or`
help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#or_fun_call